
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMA FUNCTION_NAME ID LEFT_PAR RIGHT_PAR ZERO_ARITYexpression : IDfunction_expression : ZERO_ARITYfunction_expression : FUNCTION_NAME LEFT_PAR expression RIGHT_PARexpression : function_expressionexpression : expression COMMA expression'
    
_lr_action_items = {'ID':([0,6,7,],[2,2,2,]),'ZERO_ARITY':([0,6,7,],[4,4,4,]),'FUNCTION_NAME':([0,6,7,],[5,5,5,]),'$end':([1,2,3,4,8,10,],[0,-1,-4,-2,-5,-3,]),'COMMA':([1,2,3,4,8,9,10,],[6,-1,-4,-2,6,6,-3,]),'RIGHT_PAR':([2,3,4,8,9,10,],[-1,-4,-2,-5,10,-3,]),'LEFT_PAR':([5,],[7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,6,7,],[1,8,9,]),'function_expression':([0,6,7,],[3,3,3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> ID','expression',1,'p_term_variable','parser.py',87),
  ('function_expression -> ZERO_ARITY','function_expression',1,'p_function_expression_zero_arity','parser.py',91),
  ('function_expression -> FUNCTION_NAME LEFT_PAR expression RIGHT_PAR','function_expression',4,'p_function_expression_higher_arity','parser.py',95),
  ('expression -> function_expression','expression',1,'p_expression_function','parser.py',107),
  ('expression -> expression COMMA expression','expression',3,'p_expression_expr','parser.py',111),
]
